Adicionando os exercícios: 2157, 1873, 1181 e 1101
petbccufscar/beecrowd pull request #257
Opened 2022-01-17 23:37 UTC by Vitorrecoaro

2022-01-19 17:55 UTC, matheusvictorello commented on Python/Iniciante/1101.py
> +        m = aux
```suggestion
        m, n = n, m
```

2022-01-19 18:02 UTC, matheusvictorello commented on Python/Iniciante/1101.py
> +    m, n = map(int, input().split(" "))
```suggestion
# Problema 1101 - Beecrowd - Iniciante - Nível 4

# Loop while para validar os valores de entrada e repetir o procedimento.
while True:
    # Recebendo os valores de entrada em uma mesma linha.
    m, n = map(int, input().split())

    # Condição de parada
    if m <= 0 or n <= 0:
        break

    # Coloca o menor valor do par em 'm' e o maior em 'n'
    if m > n:
        m, n = n, m
        
    # Cria a lista de números, de 'm' até 'n', ambos inclusos
    numeros = range(m, n + 1)

    # Cria o texto com os números
    texto = ' '.join(map(str, numeros))

    # Soma os números
    soma = sum(numeros)

    # Apresentação do resultado final
    print(f'{numeros} Sum={soma}')
```

2022-01-19 18:07 UTC, matheusvictorello commented on Python/Strings/1873.py
> +    elif armaGanhadora[armaRajesh].count(armaSheldon) == 0:
```suggestion
    elif armaRajesh in armaGanhadora[armaSheldon]:
```

2022-01-19 18:08 UTC, matheusvictorello commented on Python/Strings/2157.py
> +        fim = inic
```suggestion
    if inic > fim:
        inic, fim = fim, inic
```

2022-01-19 18:08 UTC, matheusvictorello commented on Python/Strings/2157.py
> +
```suggestion
```

2022-01-19 18:09 UTC, matheusvictorello commented on Python/Strings/2157.py
> +
```suggestion
    resultado = "".join(range(inic, fim + 1))

```

2022-01-19 18:11 UTC, matheusvictorello requested changes
Da uma olhada, roda lá pra ver se tá certo mesmo

2022-01-20 17:31 UTC, Vitorrecoaro reviewed
Rodei e tinha uns errinhos e já corrigi, mas creio que agora está tudo certo!

2022-01-20 17:31 UTC, Vitorrecoaro commented on Python/Iniciante/1101.py
> +    m, n = map(int, input().split(" "))
Creio que o melhor seria deste jeito
```suggestion
# Problema 1101 - Beecrowd - Iniciante - Nível 4

# Loop while para validar os valores de entrada e repetir o procedimento.
while True:
    
    # Recebendo os valores de entrada em uma mesma linha.
    m, n = map(int, input().split())
    
    # Condição de parada
    if m <= 0 or n <= 0:
        break
    
    # Coloca o menor valor do par em 'm' e o maior em 'n'
    if m > n:
        m, n = n, m
        
    # Cria a lista de números, de 'm' até 'n', ambos inclusos
    numeros = range(m, n + 1)
    
    # Cria o texto com os números
    texto = ' '.join(map(str, numeros))
    
    # Soma os números
    soma = sum(numeros)
    
    # Apresentação do resultado final
    print(f'{texto} Sum={soma}')
```

2022-01-20 17:31 UTC, Vitorrecoaro commented on Python/Iniciante/1101.py
> +    m, n = map(int, input().split(" "))
A apresentação estava errada, tinha que colocar o texto para apresentar, ao invés do "numeros".

2022-01-20 17:31 UTC, Vitorrecoaro commented on Python/Strings/2157.py
> +
O certo seria esse, né?

```suggestion
# Conversão da lista, do "inic" até o "fim", para string
    resultado = "".join(map(range(inic, fim + 1)))
```

2022-02-08 12:16 UTC, Vitorrecoaro reviewed
Fiz a checagem das mudanças e ajeitei o que estava dando errado.

2022-03-22 22:38 UTC, merged